name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-macos:
    name: Swift 6.2 on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Restore .build
        id: "restore-build"
        uses: actions/cache/restore@v4
        with:
          path: .build
          key: "swiftpm-tests-build-${{ runner.os }}-${{ github.event.pull_request.base.sha || github.event.after }}"
          restore-keys: "swiftpm-tests-build-${{ runner.os }}-"
      - name: Build
        run: swift build --build-tests --enable-code-coverage
      - name: Cache .build
        if: steps.restore-build.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: .build
          key: "swiftpm-tests-build-${{ runner.os }}-${{ github.event.pull_request.base.sha || github.event.after }}"
      - name: Run tests
        run: swift test --skip-build --enable-code-coverage --parallel
      

  build-ubuntu:
    name: Swift ${{ matrix.swift }} on Linux
    strategy:
      matrix:
        swift: ["6.2"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: ${{ matrix.swift }}
      - name: Install dependencies
        run: swift package resolve
      - name: Install zstd
        run: |
          sudo apt-get update -y
          sudo apt-get install -y zstd
      - name: Restore .build
        id: "restore-build"
        uses: actions/cache/restore@v4
        with:
          path: .build
          key: "swiftpm-tests-build-${{ runner.os }}-${{ github.event.pull_request.base.sha || github.event.after }}"
          restore-keys: "swiftpm-tests-build-${{ runner.os }}-"
      - name: Build
        run: swift build --build-tests --enable-code-coverage
      - name: Cache .build
        if: steps.restore-build.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: .build
          key: "swiftpm-tests-build-${{ runner.os }}-${{ github.event.pull_request.base.sha || github.event.after }}"
      - name: Run tests
        run: swift test --skip-build --enable-code-coverage --parallel
  
  build-windows:
    name: Swift 6.2 on Windows
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - name: Swift Install
        uses: compnerd/gha-setup-swift@main
        with:
          swift-version: swift-6.2-release
          swift-build: 6.2-RELEASE
      - name: Restore .build
        id: "restore-build"
        uses: actions/cache/restore@v4
        with:
          path: .build
          key: "swiftpm-tests-build-${{ runner.os }}-${{ github.event.pull_request.base.sha || github.event.after }}"
          restore-keys: "swiftpm-tests-build-${{ runner.os }}-"
      - name: Build
        run: swift build --build-tests --enable-code-coverage
      - name: Cache .build
        if: steps.restore-build.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: .build
          key: "swiftpm-tests-build-${{ runner.os }}-${{ github.event.pull_request.base.sha || github.event.after }}"
      - name: Run tests
        run: swift test --skip-build --enable-code-coverage --parallel

  build-android:
    name: Swift 6.2 on Android
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        uses: skiptools/swift-android-action@v2
        with:
          build-package: false
      - name: Restore .build
        id: "restore-build"
        uses: actions/cache/restore@v4
        with:
          path: .build
          key: "swiftpm-tests-build-${{ runner.os }}-${{ github.event.pull_request.base.sha || github.event.after }}"
          restore-keys: "swiftpm-tests-build-${{ runner.os }}-"
      - name: Build
        run: swift build --build-tests --enable-code-coverage
      - name: Cache .build
        if: steps.restore-build.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: .build
          key: "swiftpm-tests-build-${{ runner.os }}-${{ github.event.pull_request.base.sha || github.event.after }}"
      - name: Run tests
        run: swift test --skip-build --enable-code-coverage --parallel
